# Generated by Django 4.1.7 on 2023-03-04 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="photo",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="photos/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
    ]
