# Generated by Django 4.1.7 on 2023-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_publisher_books_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="books",
            options={
                "ordering": ["title", "publication_date"],
                "verbose_name_plural": "Books",
            },
        ),
        migrations.RemoveField(
            model_name="books",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="books",
            name="publisher",
        ),
        migrations.AddField(
            model_name="publisher",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
