# Generated by Django 4.1.7 on 2023-03-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_author_alter_books_options_remove_books_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="books.author",
            ),
        ),
        migrations.AddField(
            model_name="books",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="books.publisher",
            ),
        ),
    ]
