# Generated by Django 4.1.7 on 2023-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_books_author_alter_books_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="photo",
            field=models.ImageField(
                blank=True, default="1.png", null=True, upload_to=""
            ),
        ),
    ]
